Repository Amsterdam/signals-frontend, pull requests merged in 2021-04, with the labels that each got.

#1502 Make the incident list horizontally scrollable
  src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
Labels: bug

#1560 Convert Button component to TypeScript
  src/components/Button/__tests__/Button.test.tsx
  src/components/Button/index.tsx
Labels: enhancement

#1561 Convert ButtonBar component to TypeScript
  jest.config.js
  src/components/ButtonBar/__tests__/ButtonBar.test.tsx
  src/components/ButtonBar/index.tsx
Labels: enhancement

#1566 Upgrade to NodeJS version 16 (includes NPM v7)
  .github/workflows/ci.yml
  .nvmrc
  Dockerfile
  README.md
  e2e-tests/package-lock.json
  internals/scripts/npmcheckversion.js
  package-lock.json
  package.json
Labels: dependencies, enhancement

#1563 Convert FormFooter component to TypeScript
  src/components/FormFooter/__tests__/FormFooter.test.tsx
  src/components/FormFooter/index.tsx
Labels: enhancement

#1559 Convert AmsterdamLogo component to TypeScript
  src/components/AmsterdamLogo/__tests__/AmsterdamLogo.test.tsx
  src/components/AmsterdamLogo/index.tsx
Labels: enhancement

#1562 Convert Footer component to TypeScript
  src/components/Footer/__tests__/Footer.test.tsx
  src/components/Footer/index.tsx
Labels: enhancement
