Repository Amsterdam/signals-frontend, pull requests merged in 2021-05, with the labels that each got.

#1565 Convert GpsButton component to TypeScript
  custom.d.ts
  jest.config.js
  src/components/GPSButton/__tests__/GPSButton.test.tsx
  src/components/GPSButton/index.tsx
Labels: enhancement

#1583 [SIG-3694] Convert settings submenu to page
  e2e-tests/cypress/integration/manageSettings/manageUsers.spec.ts
  jest.config.js
  src/components/SiteHeader/__tests__/SiteHeader.test.js
  src/components/SiteHeader/index.js
  src/signals/settings/components/Overview/OverviewContainer.tsx
  src/signals/settings/components/Overview/components/Overview.tsx
  src/signals/settings/components/Overview/components/__tests__/Overview.test.tsx
  src/signals/settings/components/Overview/index.ts
  src/signals/settings/index.js
  src/signals/settings/routes.js
Labels: wip

#1606 [SIG-3710] Add 'is reported' icon to streetlights/clocks
  custom.d.ts
  src/components/MapSelect/ReportedLayer/reportedLayer.ts
  src/components/MapSelect/constants.ts
  src/components/MapSelect/index.js
  src/components/MapSelect/index.test.js
  src/shared/images/icon-reported-marker.svg
  src/signals/incident/components/IncidentPreview/components/MapSelect/index.js
  src/signals/incident/components/form/MapSelect/iconMapping.js
  src/signals/incident/definitions/wizard-step-2-vulaan/wegen-verkeer-straatmeubilair.ts
Labels: wip

#1625 [SIG-3781] Add area link to incident detail page
  src/signals/incident-management/containers/IncidentDetail/IncidentDetail.js
  src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Area/Area.tsx
  src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Area/__tests__/Area.test.tsx
  src/signals/incident-management/containers/IncidentDetail/components/Detail/components/Area/index.ts
  src/signals/incident-management/containers/IncidentDetail/components/Detail/index.js
Labels: do not merge yet
